name: Version Check

on:
  push:
    branches-ignore:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validate unique version 
        run: |
          VERSION_TAG=$(git tag | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)
          echo "Latest version tag: $VERSION_TAG"
          if [ -z "$VERSION_TAG" ]; then
            echo "No version tags found. Proceeding."
          else
            echo "Checking if version tag $VERSION_TAG already exists on this commit."
            CURRENT_COMMIT=$(git rev-parse HEAD)
            TAG_COMMIT=$(git rev-list -n 1 $VERSION_TAG)
            if [ "$CURRENT_COMMIT" = "$TAG_COMMIT" ]; then
              echo "❌ This commit is already tagged as $VERSION_TAG. Please update package.json and create a new version tag before merging to main."
              exit 1
            fi
          fi
          echo "✅ This commit is not tagged with the latest version. Proceeding."
